# Server port
server.port=8082

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/qma_db
spring.datasource.username=root
spring.datasource.password=@Avacodes0108
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT configuration
jwt.secret=0301199516011996110219972703199708082016